# Generated by Django 4.2.9 on 2024-03-10 13:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='is_good',
            field=models.BooleanField(default=False, verbose_name='признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='признак публичности'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='location',
            field=models.CharField(max_length=256, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='period',
            field=models.IntegerField(choices=[(1, 'раз в день'), (2, 'раз в 2 дня'), (3, 'раз в 3 дня'), (4, 'раз в 4 дня'), (5, 'раз в 5 дней'), (6, 'раз в 6 дней'), (7, 'раз в неделю')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(18, 50, 48, 793498), null=True, verbose_name='время выполнения'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time_to_complete',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='время на выполнение'),
        ),
    ]
